project:
  type: website
  output-dir: docs

website:
  title: "RNA-seq data analysis workflow (NZ)"
  favicon: theme_images/GA-image-black-favicon.png
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  sidebar:
    style: "docked"
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Background"
        href: background.qmd
      - text: "Sequence quality"
        href:  sequence-quality.qmd
      - text: "Index, align, quantify"
        href:  index-align-quantify.qmd
      - text: "Exploratory analysis"
        href: exploratory.qmd
      - text: "Differential gene expression"
        href: dge.qmd
      - text: "Functional analysis"
        href: functional-analysis.qmd
      - section: "Supplementary" 
        contents:
          - Supplementary/S1_hpc-job-scheduler.qmd
          - Supplementary/S2_heatmap.qmd
          - Supplementary/S3_functional.qmd


    tools:
      - icon: github
        text: Github
        href: https://github.com/otagobioinformaticsspringschool/RNA-seq-data-analysis-workflow-NZ

format:
  html:
    mainfont: "Mukta"
    monofont: "monospace"
    fontsize: 20px
    css: styles.css
    navigation: true
    page-navigation: true
    toc: true
    toc-location: right
    toc-depth: 4
    toc-title: "Contents"
    code-copy: true
    code-block-bg: true
    link-external-newwindow: true

